// Seeded demo achievements for the hackathon UI
// These are shown in the Achievements page for self-claim demo

export const DEMO_ACHIEVEMENTS = [
  {
    id: "ach_001",
    title: "Hackathon Participant",
    type: "badge",
    issuerName: "SVKM IoT Dhule",
    eventName: "Campus Hackathon 2026",
    description: "Successfully participated in the campus hackathon.",
    image: "🏆",
    color: "#f59e0b",
    gradient: "from-yellow-500 to-orange-500",
    rarity: "Common",
    points: 50,
  },
  {
    id: "ach_002",
    title: "Web3 Builder Certificate",
    type: "certificate",
    issuerName: "SVKM IoT Dhule",
    eventName: "Campus Hackathon 2026",
    description: "Certified for building a Web3 dApp using Base Sepolia, verified on-chain.",
    image: "🎓",
    color: "#6366f1",
    gradient: "from-indigo-500 to-purple-600",
    rarity: "Rare",
    points: 150,
  },
  {
    id: "ach_003",
    title: "Blockchain Innovator",
    type: "certificate",
    issuerName: "Mumbai University",
    eventName: "Blockchain Workshop 2026",
    description: "Recognized for innovative blockchain project implementation and real-world applicability.",
    image: "⛓️",
    color: "#8b5cf6",
    gradient: "from-purple-500 to-pink-500",
    rarity: "Epic",
    points: 250,
  },
  {
    id: "ach_004",
    title: "Smart Contract Developer",
    type: "badge",
    issuerName: "Base Ecosystem",
    eventName: "Base Buildathon",
    description: "Deployed and verified ERC-721 smart contracts on Base Sepolia testnet.",
    image: "📜",
    color: "#10b981",
    gradient: "from-emerald-500 to-teal-500",
    rarity: "Rare",
    points: 200,
  },
  {
    id: "ach_005",
    title: "DeFi Pioneer",
    type: "reward",
    issuerName: "TychiLabs",
    eventName: "UGF Demo Day",
    description: "Pioneered gasless DeFi interaction using Universal Gas Framework on Base network.",
    image: "🚀",
    color: "#3b82f6",
    gradient: "from-blue-500 to-cyan-500",
    rarity: "Legendary",
    points: 500,
  },
  {
    id: "ach_006",
    title: "Attendance Badge — Day 1",
    type: "badge",
    issuerName: "SVKM IoT Dhule",
    eventName: "Campus Hackathon 2026",
    description: "Attended Day 1 of the campus hackathon. Verified on-chain.",
    image: "📅",
    color: "#ec4899",
    gradient: "from-pink-500 to-rose-500",
    rarity: "Common",
    points: 25,
  },
];

export const ACHIEVEMENT_TYPES = {
  certificate: { label: "Certificate", icon: "🎓", color: "#6366f1" },
  badge:       { label: "Badge",       icon: "🏅", color: "#f59e0b" },
  reward:      { label: "Reward",      icon: "🏆", color: "#10b981" },
};

export const RARITY_COLORS = {
  Common:    "#9ca3af",
  Rare:      "#6366f1",
  Epic:      "#a855f7",
  Legendary: "#f59e0b",
};
