const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("\n🚀 Deploying CampusAchievement to Base Sepolia...");

  const [deployer] = await ethers.getSigners();

  if (!deployer) {
    console.error("❌ No deployer account found!");
    console.error("   Make sure DEPLOYER_PRIVATE_KEY is set in .env.local");
    process.exit(1);
  }

  console.log("📬 Deployer address:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Deployer balance:", ethers.formatEther(balance), "ETH");

  if (balance === 0n) {
    console.warn("⚠️  Warning: Deployer has zero balance. You may need test ETH.");
  }

  console.log("\nCompiling and deploying...");

  const CampusAchievement = await ethers.getContractFactory("CampusAchievement");
  const contract = await CampusAchievement.deploy(deployer.address);

  await contract.waitForDeployment();
  const contractAddress = await contract.getAddress();

  console.log("\n✅ CampusAchievement deployed successfully!");
  // The website treats these wallets as admins (see ADMIN_WALLETS in src/context/AuthContext.jsx).
  // Every admin who signs claim vouchers must hold MINTER_ROLE, and the main admin must be able to
  // revoke, otherwise students get "Invalid issuer signature" when they claim.
  const PRIMARY_ADMIN = process.env.PRIMARY_ADMIN || "0x42fb24C49e66e9050D8569135e69fB908e1f7292";
  const SITE_ADMINS = [
    PRIMARY_ADMIN,
    "0x220e790D10f3413a1b2Ead1f124ca2Fa497b8306",
    "0xD8bFeDAbb6eA0500d21D67caeF9E600dA21708dE",
  ];
  if (deployer.address.toLowerCase() !== PRIMARY_ADMIN.toLowerCase()) {
    console.warn("\n⚠️  Deployer is not the main admin wallet (" + PRIMARY_ADMIN + ").");
    console.warn("   Granting it admin + minter rights so vouchers and revocation keep working.");
    await (await contract.grantRole(await contract.DEFAULT_ADMIN_ROLE(), PRIMARY_ADMIN)).wait();
  }
  for (const m of SITE_ADMINS) {
    if (m.toLowerCase() === deployer.address.toLowerCase()) continue;
    await (await contract.addMinter(m)).wait();
    console.log("🔑 MINTER_ROLE granted to site admin", m);
  }

  // Optional: grant MINTER_ROLE to extra admin wallets (they sign claim vouchers).
  // Usage: EXTRA_MINTERS=0xabc...,0xdef... npm run deploy:baseSepolia
  const extra = (process.env.EXTRA_MINTERS || "").split(",").map((x) => x.trim()).filter(Boolean);
  for (const m of extra) {
    const tx = await contract.addMinter(m);
    await tx.wait();
    console.log("🔑 MINTER_ROLE granted to", m);
  }
  console.log("📍 Contract Address:", contractAddress);
  console.log("🔗 BaseScan:", `https://sepolia.basescan.org/address/${contractAddress}`);

  // Write config
  const configPath = path.join(__dirname, "../src/config/contract.js");
  const artifactPath = path.join(__dirname, "../artifacts/contracts/CampusAchievement.sol/CampusAchievement.json");

  const abi = JSON.parse(fs.readFileSync(artifactPath)).abi;

  const configContent = `// AUTO-GENERATED by scripts/deploy.cjs — DO NOT EDIT MANUALLY
// Deployed on: ${new Date().toISOString()}

export const CONTRACT_ADDRESS = "${contractAddress}";
export const DEPLOYER_ADDRESS = "${deployer.address}";
export const CHAIN_ID = 84532;
export const NETWORK_NAME = "Base Sepolia";
export const EXPLORER_URL = "https://sepolia.basescan.org";

export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)};
`;

  fs.writeFileSync(configPath, configContent);
  console.log("\n📝 Contract config updated → src/config/contract.js");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Deployment failed:");
    console.error(error);
    process.exit(1);
  });